language: cpp
dist: bionic
compiler:
- gcc
os:
- linux


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-10
    - g++-10
    - cmake
    - doxygen
    update: true
    
before_install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.0-rc3/cmake-3.15.0-rc3-Linux-x86_64.tar.gz
  - tar -xf cmake-3.15.0-rc3-Linux-x86_64.tar.gz
  - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.15.0-rc3-Linux-x86_64/bin/cmake /home/travis/bin/cmake
  - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.15.0-rc3-Linux-x86_64/bin/ctest /home/travis/bin/ctest
  - export CXX=/usr/bin/g++-10 
  - export CC=/usr/bin/gcc-10
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - cmake --version
  - export VCPKG_TRIPLET=x64-linux
  - export VCPKG_ROOT=${HOME}/deps/vcpkg
  
install:
   # Install vcpkg and dependencies
  - |
    set -e
    mkdir -p ${VCPKG_ROOT}
    pushd ${VCPKG_ROOT}
    git init
    git remote add origin https://github.com/Microsoft/vcpkg.git
    git fetch origin master
    git checkout -b master origin/master
    ./bootstrap-vcpkg.sh
    # Only build release libs to save time. We inject a new line first since some cmake files don't end with one.
    echo -e '\nset(VCPKG_BUILD_TYPE release)' >> ./triplets/${VCPKG_TRIPLET}.cmake
    ./vcpkg install boost-math eigen3
    popd

script:
  - cmake .
  - cmake --build . -j2 
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5
